import Image from "next/image";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ArrowRightIcon, CheckIcon, ComputerDesktopIcon, CpuChipIcon, DevicePhoneMobileIcon, ShieldCheckIcon, WrenchScrewdriverIcon } from "@/components/icons";

const services = [
  { title: "Soporte técnico", text: "Diagnóstico y reparación confiable para mantener tu tecnología en marcha.", icon: WrenchScrewdriverIcon },
  { title: "Equipos y accesorios", text: "Encuentra opciones seleccionadas para tu hogar, estudio o negocio.", icon: ComputerDesktopIcon },
  { title: "Soluciones para empresas", text: "Asesoría para armar una operación tecnológica segura y eficiente.", icon: CpuChipIcon },
];
const products = [
  { name: "Laptop para trabajo", type: "Rendimiento para cada día", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80" },
  { name: "Accesorios esenciales", type: "Conecta, protege y mejora", image: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80" },
  { name: "Tecnología móvil", type: "Siempre a tu alcance", image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80" },
];

export default function Home() {
  return <main><section id="inicio" className="grid-glow relative overflow-hidden text-white"><Navbar /><div className="mx-auto grid min-h-[720px] max-w-7xl items-center gap-12 px-6 pb-20 pt-32 lg:grid-cols-2 lg:px-8"><div className="relative z-10"><p className="eyebrow">Tecnología sin complicaciones</p><h1 className="mt-5 max-w-xl text-5xl font-black leading-[1.02] tracking-tight sm:text-6xl">Tu tecnología merece <span className="text-brand">respaldo real.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-300">Equipos, accesorios y soporte técnico con la atención cercana que necesitas para avanzar con confianza.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#contacto" className="inline-flex items-center gap-2 rounded-full bg-brand px-6 py-3.5 font-bold transition hover:bg-orange-500">Hablar con un asesor <ArrowRightIcon className="size-4" /></a><a href="#servicios" className="rounded-full border border-white/25 px-6 py-3.5 font-bold transition hover:bg-white/10">Conoce nuestros servicios</a></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-4 text-sm font-semibold text-slate-300"><span className="inline-flex items-center gap-2"><CheckIcon className="size-4 text-brand" /> Atención personalizada</span><span className="inline-flex items-center gap-2"><CheckIcon className="size-4 text-brand" /> Soluciones a medida</span></div></div><div className="relative"><div className="absolute -inset-4 rounded-[2.5rem] bg-brand/20 blur-3xl"/><Image className="relative h-[390px] w-full rounded-[2rem] object-cover shadow-2xl lg:h-[480px]" src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1100&q=85" alt="Persona trabajando con una laptop" width={1100} height={900} priority /><div className="absolute -bottom-6 -left-4 rounded-2xl bg-white p-5 text-ink shadow-card sm:left-8"><p className="text-2xl font-black">+10 años</p><p className="text-sm text-slate-500">acompañando clientes</p></div></div></div></section>

  <section id="servicios" className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><p className="eyebrow">Lo que hacemos</p><div className="mt-3 flex flex-col justify-between gap-6 md:flex-row md:items-end"><h2 className="max-w-xl text-4xl font-black tracking-tight sm:text-5xl">Soluciones que hacen que todo funcione mejor.</h2><p className="max-w-sm leading-7 text-slate-600">Te ayudamos a elegir, resolver y aprovechar la tecnología sin perder tiempo.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{services.map(({title,text,icon: Icon}) => <article key={title} className="group rounded-3xl border border-slate-200 p-8 transition hover:-translate-y-1 hover:border-brand hover:shadow-card"><Icon className="size-9 text-brand" /><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p><a href="#contacto" className="mt-7 inline-flex items-center gap-2 font-bold text-brand">Consultar <ArrowRightIcon className="size-4 transition group-hover:translate-x-1"/></a></article>)}</div></section>

  <section id="productos" className="bg-mist py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Próximamente catálogo</p><h2 className="mt-3 text-4xl font-black tracking-tight">Tecnología para elegir bien.</h2></div><a href="#contacto" className="font-bold text-brand">Solicita disponibilidad →</a></div><div className="mt-12 grid gap-6 md:grid-cols-3">{products.map(product => <article key={product.name} className="overflow-hidden rounded-3xl bg-white shadow-sm"><Image src={product.image} alt={product.name} width={900} height={600} className="h-56 w-full object-cover"/><div className="p-6"><p className="text-sm text-slate-500">{product.type}</p><h3 className="mt-1 text-xl font-bold">{product.name}</h3><button className="mt-5 text-sm font-bold text-brand">Ver opciones →</button></div></article>)}</div></div></section>

  <section id="nosotros" className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow">La diferencia SOTEC</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Hablamos claro. Respondemos rápido. Cumplimos.</h2><p className="mt-6 max-w-xl leading-8 text-slate-600">No vendemos tecnología por vender. Escuchamos lo que necesitas y te proponemos una solución que tenga sentido para ti.</p><div className="mt-8 space-y-5">{[[ShieldCheckIcon,"Compra y soporte con confianza"],[DevicePhoneMobileIcon,"Atención simple por WhatsApp"],[CheckIcon,"Recomendaciones honestas"]].map(([Icon,label]) => { const ItemIcon = Icon as typeof CheckIcon; return <div key={label as string} className="flex items-center gap-4"><span className="rounded-full bg-orange-50 p-3"><ItemIcon className="size-5 text-brand"/></span><span className="font-bold">{label as string}</span></div>})}</div></div><div className="rounded-[2rem] bg-ink p-10 text-white"><p className="text-brand">NUESTRA PROMESA</p><blockquote className="mt-8 text-3xl font-bold leading-tight">“Que cada solución tecnológica se sienta sencilla, segura y acertada.”</blockquote><div className="mt-16 border-t border-white/15 pt-6 text-sm text-slate-400">Equipo SOTEC Service</div></div></section>

  <section id="contacto" className="px-6 pb-24 lg:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-brand px-8 py-14 text-white md:px-14 md:py-16"><div className="max-w-2xl"><p className="text-sm font-bold tracking-[.16em]">¿TIENES UNA CONSULTA?</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Cuéntanos qué necesitas. Estamos para ayudarte.</h2><p className="mt-5 text-lg text-orange-50">Escríbenos y recibe orientación personalizada para tu compra, reparación o proyecto.</p><a href={process.env.NEXT_PUBLIC_WHATSAPP_URL || "https://wa.me/51999999999"} className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-bold text-ink transition hover:bg-orange-50">Contactar por WhatsApp <ArrowRightIcon className="size-4"/></a></div></div></section><Footer /></main>;
}
